server:
  port: 8090
  servlet:
    context-path: /web

#spring:
#  datasource:
#    username: root
#    password: wdsjnsjydjy
#    url: jdbc:mysql://cdb-kc7z7ask.cd.tencentcdb.com:10027/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test28?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update